services:
  chat-backend:
    container_name: chat-backend
    build: ./api_server
    restart: unless-stopped
    networks: [email_network, nginx_network, db_network]
    env_file:
      - ./api_server/.env

  chat-frontend:
    container_name: chat-frontend
    build: ./frontend
    networks: [nginx_network]
    restart: unless-stopped

  websocket:
    container_name: chat-websocket
    build: ./socket_server
    restart: unless-stopped
    networks: [nginx_network, db_network]
    env_file:
      - ./socket_server/.env


networks:
  nginx_network:
    external: true
  email_network:
    external: true
  db_network:
    external: true