export const emoji = [
   {
      title: "Smileys & People",
      list: [
         { emoji: "😀", name: "Grinning Face" },
         { emoji: "😁", name: "Beaming Face With Smiling Eyes" },
         { emoji: "😂", name: "Face With Tears Of Joy" },
         { emoji: "🤣", name: "Rolling On The Floor Laughing" },
         { emoji: "😃", name: "Grinning Face With Big Eyes" },
         { emoji: "😄", name: "Grinning Face With Smiling Eyes" },
         { emoji: "😅", name: "Grinning Face With Sweat" },
         { emoji: "😆", name: "Grinning Squinting Face" },
         { emoji: "😉", name: "Winking Face" },
         { emoji: "😊", name: "Smiling Face With Smiling Eyes" },
         { emoji: "🥰", name: "Smiling Face with Hearts" },
         { emoji: "😋", name: "Face Savoring Food" },
         { emoji: "😎", name: "Smiling Face With Sunglasses" },
         { emoji: "😍", name: "Smiling Face With Heart-Eyes" },
         { emoji: "😘", name: "Face Blowing A Kiss" },
         { emoji: "😗", name: "Kissing Face" },
         { emoji: "😙", name: "Kissing Face With Smiling Eyes" },
         { emoji: "😚", name: "Kissing Face With Closed Eyes" },
         { emoji: "☺️", name: "Smiling Face" },
         { emoji: "🙂", name: "Slightly Smiling Face" },
         { emoji: "🤗", name: "Hugging Face" },
         { emoji: "🤩", name: "Star-Struck" },
         { emoji: "🤔", name: "Thinking Face" },
         { emoji: "🤨", name: "Face With Raised Eyebrow" },
         { emoji: "😐", name: "Neutral Face" },
         { emoji: "😑", name: "Expressionless Face" },
         { emoji: "😶", name: "Face Without Mouth" },
         { emoji: "🙄", name: "Face With Rolling Eyes" },
         { emoji: "😏", name: "Smirking Face" },
         { emoji: "😣", name: "Persevering Face" },
         { emoji: "😥", name: "Sad But Relieved Face" },
         { emoji: "😮", name: "Face With Open Mouth" },
         { emoji: "🤐", name: "Zipper-Mouth Face" },
         { emoji: "😯", name: "Hushed Face" },
         { emoji: "😪", name: "Sleepy Face" },
         { emoji: "😫", name: "Tired Face" },
         { emoji: "🥱", name: "Yawning Face" },
         { emoji: "😴", name: "Sleeping Face" },
         { emoji: "😌", name: "Relieved Face" },
         { emoji: "😛", name: "Face With Tongue" },
         { emoji: "😜", name: "Winking Face With Tongue" },
         { emoji: "😝", name: "Squinting Face With Tongue" },
         { emoji: "🤤", name: "Drooling Face" },
         { emoji: "😒", name: "Unamused Face" },
         { emoji: "😓", name: "Downcast Face With Sweat" },
         { emoji: "😔", name: "Pensive Face" },
         { emoji: "😕", name: "Confused Face" },
         { emoji: "🙃", name: "Upside-Down Face" },
         { emoji: "🤑", name: "Money-Mouth Face" },
         { emoji: "😲", name: "Astonished Face" },
         { emoji: "☹️", name: "Frowning Face" },
         { emoji: "🙁", name: "Slightly Frowning Face" },
         { emoji: "😖", name: "Confounded Face" },
         { emoji: "😞", name: "Disappointed Face" },
         { emoji: "😟", name: "Worried Face" },
         { emoji: "😤", name: "Face With Steam From Nose" },
         { emoji: "😢", name: "Crying Face" },
         { emoji: "😭", name: "Loudly Crying Face" },
         { emoji: "😦", name: "Frowning Face With Open Mouth" },
         { emoji: "😧", name: "Anguished Face" },
         { emoji: "😨", name: "Fearful Face" },
         { emoji: "😩", name: "Weary Face" },
         { emoji: "🤯", name: "Exploding Head" },
         { emoji: "😬", name: "Grimacing Face" },
         { emoji: "😰", name: "Anxious Face With Sweat" },
         { emoji: "😱", name: "Face Screaming In Fear" },
         { emoji: "😳", name: "Flushed Face" },
         { emoji: "🤪", name: "Zany Face" },
         { emoji: "😵", name: "Dizzy Face" },
         { emoji: "😡", name: "Pouting Face" },
         { emoji: "😠", name: "Angry Face" },
         { emoji: "🤬", name: "Face With Symbols On Mouth" },
         { emoji: "😷", name: "Face With Medical Mask" },
         { emoji: "🤒", name: "Face With Thermometer" },
         { emoji: "🤕", name: "Face With Head-Bandage" },
         { emoji: "🤢", name: "Nauseated Face" },
         { emoji: "🤮", name: "Face Vomiting" },
         { emoji: "🤧", name: "Sneezing Face" },
         { emoji: "😇", name: "Smiling Face With Halo" },
         { emoji: "🤠", name: "Cowboy Hat Face" },
         { emoji: "🤥", name: "Lying Face" },
         { emoji: "🤫", name: "Shushing Face" },
         { emoji: "🤭", name: "Face With Hand Over Mouth" },
         { emoji: "🧐", name: "Face With Monocle" },
         { emoji: "🤓", name: "Nerd Face" },
         { emoji: "😈", name: "Smiling Face With Horns" },
         { emoji: "👿", name: "Angry Face With Horns" },
         { emoji: "🤡", name: "Clown Face" },
         { emoji: "👹", name: "Ogre" },
         { emoji: "👺", name: "Goblin" },
         { emoji: "💀", name: "Skull" },
         { emoji: "☠️", name: "Skull And Crossbones" },
         { emoji: "👻", name: "Ghost" },
         { emoji: "👽", name: "Alien" },
         { emoji: "👾", name: "Alien Monster" },
         { emoji: "🤖", name: "Robot Face" },
         { emoji: "💩", name: "Pile Of Poo" },
         { emoji: "😺", name: "Grinning Cat Face" },
         { emoji: "😸", name: "Grinning Cat Face With Smiling Eyes" },
         { emoji: "😹", name: "Cat Face With Tears Of Joy" },
         { emoji: "😻", name: "Smiling Cat Face With Heart-Eyes" },
         { emoji: "😼", name: "Cat Face With Wry Smile" },
         { emoji: "😽", name: "Kissing Cat Face" },
         { emoji: "🙀", name: "Weary Cat Face" },
         { emoji: "😿", name: "Crying Cat Face" },
         { emoji: "😾", name: "Pouting Cat Face" },
         { emoji: "🙈", name: "See-No-Evil Monkey" },
         { emoji: "🙉", name: "Hear-No-Evil Monkey" },
         { emoji: "🙊", name: "Speak-No-Evil Monkey" },
         { emoji: "🏻", name: "Light Skin Tone" },
         { emoji: "🏼", name: "Medium-Light Skin Tone" },
         { emoji: "🏽", name: "Medium Skin Tone" },
         { emoji: "🏾", name: "Medium-Dark Skin Tone" },
         { emoji: "🏿", name: "Dark Skin Tone" },
         { emoji: "👶", name: "Baby" },
         { emoji: "🧒", name: "Child" },
         { emoji: "👦", name: "Boy" },
         { emoji: "👧", name: "Girl" },
         { emoji: "🧑", name: "Adult" },
         { emoji: "👨", name: "Man" },
         { emoji: "👩", name: "Woman" },
         { emoji: "🧓", name: "Older Adult" },
         { emoji: "👴", name: "Old Man" },
         { emoji: "👵", name: "Old Woman" },
         { emoji: "👨\u200d⚕️", name: "Man Health Worker" },
         { emoji: "👩\u200d⚕️", name: "Woman Health Worker" },
         { emoji: "👨\u200d🎓", name: "Man Student" },
         { emoji: "👩\u200d🎓", name: "Woman Student" },
         { emoji: "👨\u200d🏫", name: "Man Teacher" },
         { emoji: "👩\u200d🏫", name: "Woman Teacher" },
         { emoji: "👨\u200d⚖️", name: "Man Judge" },
         { emoji: "👩\u200d⚖️", name: "Woman Judge" },
         { emoji: "👨\u200d🌾", name: "Man Farmer" },
         { emoji: "👩\u200d🌾", name: "Woman Farmer" },
         { emoji: "👨\u200d🍳", name: "Man Cook" },
         { emoji: "👩\u200d🍳", name: "Woman Cook" },
         { emoji: "👨\u200d🔧", name: "Man Mechanic" },
         { emoji: "👩\u200d🔧", name: "Woman Mechanic" },
         { emoji: "👨\u200d🏭", name: "Man Factory Worker" },
         { emoji: "👩\u200d🏭", name: "Woman Factory Worker" },
         { emoji: "👨\u200d💼", name: "Man Office Worker" },
         { emoji: "👩\u200d💼", name: "Woman Office Worker" },
         { emoji: "👨\u200d🔬", name: "Man Scientist" },
         { emoji: "👩\u200d🔬", name: "Woman Scientist" },
         { emoji: "👨\u200d💻", name: "Man Technologist" },
         { emoji: "👩\u200d💻", name: "Woman Technologist" },
         { emoji: "👨\u200d🎤", name: "Man Singer" },
         { emoji: "👩\u200d🎤", name: "Woman Singer" },
         { emoji: "👨\u200d🎨", name: "Man Artist" },
         { emoji: "👩\u200d🎨", name: "Woman Artist" },
         { emoji: "👨\u200d✈️", name: "Man Pilot" },
         { emoji: "👩\u200d✈️", name: "Woman Pilot" },
         { emoji: "👨\u200d🚀", name: "Man Astronaut" },
         { emoji: "👩\u200d🚀", name: "Woman Astronaut" },
         { emoji: "👨\u200d🚒", name: "Man Firefighter" },
         { emoji: "👩\u200d🚒", name: "Woman Firefighter" },
         { emoji: "👮", name: "Police Officer" },
         { emoji: "👮\u200d♂️", name: "Man Police Officer" },
         { emoji: "👮\u200d♀️", name: "Woman Police Officer" },
         { emoji: "🕵️", name: "Detective" },
         { emoji: "🕵️\u200d♂️", name: "Man Detective" },
         { emoji: "🕵️\u200d♀️", name: "Woman Detective" },
         { emoji: "💂", name: "Guard" },
         { emoji: "💂\u200d♂️", name: "Man Guard" },
         { emoji: "💂\u200d♀️", name: "Woman Guard" },
         { emoji: "👷", name: "Construction Worker" },
         { emoji: "👷\u200d♂️", name: "Man Construction Worker" },
         { emoji: "👷\u200d♀️", name: "Woman Construction Worker" },
         { emoji: "🤴", name: "Prince" },
         { emoji: "👸", name: "Princess" },
         { emoji: "👳", name: "Person Wearing Turban" },
         { emoji: "👳\u200d♂️", name: "Man Wearing Turban" },
         { emoji: "👳\u200d♀️", name: "Woman Wearing Turban" },
         { emoji: "👲", name: "Man With Chinese Cap" },
         { emoji: "🧕", name: "Woman With Headscarf" },
         { emoji: "🧔", name: "Bearded Person" },
         { emoji: "👱\u200d♂️", name: "Blond-Haired Man" },
         { emoji: "👱\u200d♀️", name: "Blond-Haired Woman" },
         { emoji: "🤵", name: "Man In Tuxedo" },
         { emoji: "👰", name: "Bride With Veil" },
         { emoji: "🤰", name: "Pregnant Woman" },
         { emoji: "🤱", name: "Breast-Feeding" },
         { emoji: "👼", name: "Baby Angel" },
         { emoji: "🎅", name: "Santa Claus" },
         { emoji: "🤶", name: "Mrs. Claus" },
         { emoji: "🧙", name: "Mage" },
         { emoji: "🧙\u200d♀️", name: "Woman Mage" },
         { emoji: "🧙\u200d♂️", name: "Man Mage" },
         { emoji: "🧚", name: "Fairy" },
         { emoji: "🧚\u200d♀️", name: "Woman Fairy" },
         { emoji: "🧚\u200d♂️", name: "Man Fairy" },
         { emoji: "🧛", name: "Vampire" },
         { emoji: "🧛\u200d♀️", name: "Woman Vampire" },
         { emoji: "🧛\u200d♂️", name: "Man Vampire" },
         { emoji: "🧜", name: "Merperson" },
         { emoji: "🧜\u200d♀️", name: "Mermaid" },
         { emoji: "🧜\u200d♂️", name: "Merman" },
         { emoji: "🧝", name: "Elf" },
         { emoji: "🧝\u200d♀️", name: "Woman Elf" },
         { emoji: "🧝\u200d♂️", name: "Man Elf" },
         { emoji: "🧞", name: "Genie" },
         { emoji: "🧞\u200d♀️", name: "Woman Genie" },
         { emoji: "🧞\u200d♂️", name: "Man Genie" },
         { emoji: "🧟", name: "Zombie" },
         { emoji: "🧟\u200d♀️", name: "Woman Zombie" },
         { emoji: "🧟\u200d♂️", name: "Man Zombie" },
         { emoji: "🙍", name: "Person Frowning" },
         { emoji: "🙍\u200d♂️", name: "Man Frowning" },
         { emoji: "🙍\u200d♀️", name: "Woman Frowning" },
         { emoji: "🙎", name: "Person Pouting" },
         { emoji: "🙎\u200d♂️", name: "Man Pouting" },
         { emoji: "🙎\u200d♀️", name: "Woman Pouting" },
         { emoji: "🙅", name: "Person Gesturing No" },
         { emoji: "🙅\u200d♂️", name: "Man Gesturing No" },
         { emoji: "🙅\u200d♀️", name: "Woman Gesturing No" },
         { emoji: "🙆", name: "Person Gesturing Ok" },
         { emoji: "🙆\u200d♂️", name: "Man Gesturing Ok" },
         { emoji: "🙆\u200d♀️", name: "Woman Gesturing Ok" },
         { emoji: "💁", name: "Person Tipping Hand" },
         { emoji: "💁\u200d♂️", name: "Man Tipping Hand" },
         { emoji: "💁\u200d♀️", name: "Woman Tipping Hand" },
         { emoji: "🙋", name: "Person Raising Hand" },
         { emoji: "🙋\u200d♂️", name: "Man Raising Hand" },
         { emoji: "🙋\u200d♀️", name: "Woman Raising Hand" },
         { emoji: "🙇", name: "Person Bowing" },
         { emoji: "🙇\u200d♂️", name: "Man Bowing" },
         { emoji: "🙇\u200d♀️", name: "Woman Bowing" },
         { emoji: "🤦", name: "Person Facepalming" },
         { emoji: "🤦\u200d♂️", name: "Man Facepalming" },
         { emoji: "🤦\u200d♀️", name: "Woman Facepalming" },
         { emoji: "🤷", name: "Person Shrugging" },
         { emoji: "🤷\u200d♂️", name: "Man Shrugging" },
         { emoji: "🤷\u200d♀️", name: "Woman Shrugging" },
         { emoji: "💆", name: "Person Getting Massage" },
         { emoji: "💆\u200d♂️", name: "Man Getting Massage" },
         { emoji: "💆\u200d♀️", name: "Woman Getting Massage" },
         { emoji: "💇", name: "Person Getting Haircut" },
         { emoji: "💇\u200d♂️", name: "Man Getting Haircut" },
         { emoji: "💇\u200d♀️", name: "Woman Getting Haircut" },
         { emoji: "🚶", name: "Person Walking" },
         { emoji: "🚶\u200d♂️", name: "Man Walking" },
         { emoji: "🚶\u200d♀️", name: "Woman Walking" },
         { emoji: "🏃", name: "Person Running" },
         { emoji: "🏃\u200d♂️", name: "Man Running" },
         { emoji: "🏃\u200d♀️", name: "Woman Running" },
         { emoji: "💃", name: "Woman Dancing" },
         { emoji: "🕺", name: "Man Dancing" },
         { emoji: "👯", name: "People With Bunny Ears" },
         { emoji: "👯\u200d♂️", name: "Men With Bunny Ears" },
         { emoji: "👯\u200d♀️", name: "Women With Bunny Ears" },
         { emoji: "🧖", name: "Person In Steamy Room" },
         { emoji: "🧖\u200d♀️", name: "Woman In Steamy Room" },
         { emoji: "🧖\u200d♂️", name: "Man In Steamy Room" },
         { emoji: "🧗", name: "Person Climbing" },
         { emoji: "🧗\u200d♀️", name: "Woman Climbing" },
         { emoji: "🧗\u200d♂️", name: "Man Climbing" },
         { emoji: "🧘", name: "Person In Lotus Position" },
         { emoji: "🧘\u200d♀️", name: "Woman In Lotus Position" },
         { emoji: "🧘\u200d♂️", name: "Man In Lotus Position" },
         { emoji: "🛀", name: "Person Taking Bath" },
         { emoji: "🛌", name: "Person In Bed" },
         { emoji: "🕴️", name: "Man In Suit Levitating" },
         { emoji: "🗣️", name: "Speaking Head" },
         { emoji: "👤", name: "Bust In Silhouette" },
         { emoji: "👥", name: "Busts In Silhouette" },
         { emoji: "🤺", name: "Person Fencing" },
         { emoji: "🏇", name: "Horse Racing" },
         { emoji: "⛷️", name: "Skier" },
         { emoji: "🏂", name: "Snowboarder" },
         { emoji: "🏌️", name: "Person Golfing" },
         { emoji: "🏌️\u200d♂️", name: "Man Golfing" },
         { emoji: "🏌️\u200d♀️", name: "Woman Golfing" },
         { emoji: "🏄", name: "Person Surfing" },
         { emoji: "🏄\u200d♂️", name: "Man Surfing" },
         { emoji: "🏄\u200d♀️", name: "Woman Surfing" },
         { emoji: "🚣", name: "Person Rowing Boat" },
         { emoji: "🚣\u200d♂️", name: "Man Rowing Boat" },
         { emoji: "🚣\u200d♀️", name: "Woman Rowing Boat" },
         { emoji: "🏊", name: "Person Swimming" },
         { emoji: "🏊\u200d♂️", name: "Man Swimming" },
         { emoji: "🏊\u200d♀️", name: "Woman Swimming" },
         { emoji: "⛹️", name: "Person Bouncing Ball" },
         { emoji: "⛹️\u200d♂️", name: "Man Bouncing Ball" },
         { emoji: "⛹️\u200d♀️", name: "Woman Bouncing Ball" },
         { emoji: "🏋️", name: "Person Lifting Weights" },
         { emoji: "🏋️\u200d♂️", name: "Man Lifting Weights" },
         { emoji: "🏋️\u200d♀️", name: "Woman Lifting Weights" },
         { emoji: "🚴", name: "Person Biking" },
         { emoji: "🚴\u200d♂️", name: "Man Biking" },
         { emoji: "🚴\u200d♀️", name: "Woman Biking" },
         { emoji: "🚵", name: "Person Mountain Biking" },
         { emoji: "🚵\u200d♂️", name: "Man Mountain Biking" },
         { emoji: "🚵\u200d♀️", name: "Woman Mountain Biking" },
         { emoji: "🏎️", name: "Racing Car" },
         { emoji: "🏍️", name: "Motorcycle" },
         { emoji: "🤸", name: "Person Cartwheeling" },
         { emoji: "🤸\u200d♂️", name: "Man Cartwheeling" },
         { emoji: "🤸\u200d♀️", name: "Woman Cartwheeling" },
         { emoji: "🤼", name: "People Wrestling" },
         { emoji: "🤼\u200d♂️", name: "Men Wrestling" },
         { emoji: "🤼\u200d♀️", name: "Women Wrestling" },
         { emoji: "🤽", name: "Person Playing Water Polo" },
         { emoji: "🤽\u200d♂️", name: "Man Playing Water Polo" },
         { emoji: "🤽\u200d♀️", name: "Woman Playing Water Polo" },
         { emoji: "🤾", name: "Person Playing Handball" },
         { emoji: "🤾\u200d♂️", name: "Man Playing Handball" },
         { emoji: "🤾\u200d♀️", name: "Woman Playing Handball" },
         { emoji: "🤹", name: "Person Juggling" },
         { emoji: "🤹\u200d♂️", name: "Man Juggling" },
         { emoji: "🤹\u200d♀️", name: "Woman Juggling" },
         { emoji: "👫", name: "Man And Woman Holding Hands" },
         { emoji: "👬", name: "Two Men Holding Hands" },
         { emoji: "👭", name: "Two Women Holding Hands" },
         { emoji: "💏", name: "Kiss" },
         { emoji: "💑", name: "Couple With Heart" },
         { emoji: "👪", name: "Family" },
         { emoji: "🤳", name: "Selfie" },
         { emoji: "💪", name: "Flexed Biceps" },
         { emoji: "👈", name: "Backhand Index Pointing Left" },
         { emoji: "👉", name: "Backhand Index Pointing Right" },
         { emoji: "☝️", name: "Index Pointing Up" },
         { emoji: "👆", name: "Backhand Index Pointing Up" },
         { emoji: "🖕", name: "Middle Finger" },
         { emoji: "👇", name: "Backhand Index Pointing Down" },
         { emoji: "✌️", name: "Victory Hand" },
         { emoji: "🤞", name: "Crossed Fingers" },
         { emoji: "🖖", name: "Vulcan Salute" },
         { emoji: "🤘", name: "Sign Of The Horns" },
         { emoji: "🤙", name: "Call Me Hand" },
         { emoji: "🖐️", name: "Hand With Fingers Splayed" },
         { emoji: "✋", name: "Raised Hand" },
         { emoji: "👌", name: "Ok Hand" },
         { emoji: "👍", name: "Thumbs Up" },
         { emoji: "👎", name: "Thumbs Down" },
         { emoji: "✊", name: "Raised Fist" },
         { emoji: "👊", name: "Oncoming Fist" },
         { emoji: "🤛", name: "Left-Facing Fist" },
         { emoji: "🤜", name: "Right-Facing Fist" },
         { emoji: "🤚", name: "Raised Back Of Hand" },
         { emoji: "👋", name: "Waving Hand" },
         { emoji: "🤟", name: "Love-You Gesture" },
         { emoji: "✍️", name: "Writing Hand" },
         { emoji: "👏", name: "Clapping Hands" },
         { emoji: "👐", name: "Open Hands" },
         { emoji: "🙌", name: "Raising Hands" },
         { emoji: "🤲", name: "Palms Up Together" },
         { emoji: "🙏", name: "Folded Hands" },
         { emoji: "🤝", name: "Handshake" },
         { emoji: "💅", name: "Nail Polish" },
         { emoji: "👂", name: "Ear" },
         { emoji: "👃", name: "Nose" },
         { emoji: "👣", name: "Footprints" },
         { emoji: "👀", name: "Eyes" },
         { emoji: "👁️", name: "Eye" },
         { emoji: "👁️\u200d🗨️", name: "Eye In Speech Bubble" },
         { emoji: "🧠", name: "Brain" },
         { emoji: "👅", name: "Tongue" },
         { emoji: "👄", name: "Mouth" },
         { emoji: "💋", name: "Kiss Mark" },
         { emoji: "💘", name: "Heart With Arrow" },
         { emoji: "❤️", name: "Red Heart" },
         { emoji: "💓", name: "Beating Heart" },
         { emoji: "💔", name: "Broken Heart" },
         { emoji: "💕", name: "Two Hearts" },
         { emoji: "💖", name: "Sparkling Heart" },
         { emoji: "💗", name: "Growing Heart" },
         { emoji: "💙", name: "Blue Heart" },
         { emoji: "💚", name: "Green Heart" },
         { emoji: "💛", name: "Yellow Heart" },
         { emoji: "🧡", name: "Orange Heart" },
         { emoji: "💜", name: "Purple Heart" },
         { emoji: "🖤", name: "Black Heart" },
         { emoji: "🤍", name: "White Heart" },
         { emoji: "🤎", name: "Brown Heart" },
         { emoji: "💝", name: "Heart With Ribbon" },
         { emoji: "💞", name: "Revolving Hearts" },
         { emoji: "💟", name: "Heart Decoration" },
         { emoji: "❣️", name: "Heavy Heart Exclamation" },
         { emoji: "💌", name: "Love Letter" },
         { emoji: "💤", name: "Zzz" },
         { emoji: "💢", name: "Anger Symbol" },
         { emoji: "💣", name: "Bomb" },
         { emoji: "💥", name: "Collision" },
         { emoji: "💦", name: "Sweat Droplets" },
         { emoji: "💨", name: "Dashing Away" },
         { emoji: "💫", name: "Dizzy" },
         { emoji: "💬", name: "Speech Balloon" },
         { emoji: "🗨️", name: "Left Speech Bubble" },
         { emoji: "🗯️", name: "Right Anger Bubble" },
         { emoji: "💭", name: "Thought Balloon" },
         { emoji: "🕳️", name: "Hole" },
         { emoji: "👓", name: "Glasses" },
         { emoji: "🕶️", name: "Sunglasses" },
         { emoji: "👔", name: "Necktie" },
         { emoji: "👕", name: "T-Shirt" },
         { emoji: "👖", name: "Jeans" },
         { emoji: "🧣", name: "Scarf" },
         { emoji: "🧤", name: "Gloves" },
         { emoji: "🧥", name: "Coat" },
         { emoji: "🧦", name: "Socks" },
         { emoji: "👗", name: "Dress" },
         { emoji: "👘", name: "Kimono" },
         { emoji: "👙", name: "Bikini" },
         { emoji: "👚", name: "Woman's Clothes" },
         { emoji: "👛", name: "Purse" },
         { emoji: "👜", name: "Handbag" },
         { emoji: "👝", name: "Clutch Bag" },
         { emoji: "🛍️", name: "Shopping Bags" },
         { emoji: "🎒", name: "School Backpack" },
         { emoji: "👞", name: "Man's Shoe" },
         { emoji: "👟", name: "Running Shoe" },
         { emoji: "👠", name: "High-Heeled Shoe" },
         { emoji: "👡", name: "Woman's Sandal" },
         { emoji: "👢", name: "Woman's Boot" },
         { emoji: "👑", name: "Crown" },
         { emoji: "👒", name: "Woman's Hat" },
         { emoji: "🎩", name: "Top Hat" },
         { emoji: "🎓", name: "Graduation Cap" },
         { emoji: "🧢", name: "Billed Cap" },
         { emoji: "⛑️", name: "Rescue Worker's Helmet" },
         { emoji: "📿", name: "Prayer Beads" },
         { emoji: "💄", name: "Lipstick" },
         { emoji: "💍", name: "Ring" },
         { emoji: "💎", name: "Gem Stone" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Animals & Nature",
      list: [
         { emoji: "🐵", name: "Monkey Face" },
         { emoji: "🐒", name: "Monkey" },
         { emoji: "🦍", name: "Gorilla" },
         { emoji: "🐶", name: "Dog Face" },
         { emoji: "🐕", name: "Dog" },
         { emoji: "🐩", name: "Poodle" },
         { emoji: "🐺", name: "Wolf Face" },
         { emoji: "🦊", name: "Fox Face" },
         { emoji: "🐱", name: "Cat Face" },
         { emoji: "🐈", name: "Cat" },
         { emoji: "🦁", name: "Lion Face" },
         { emoji: "🐯", name: "Tiger Face" },
         { emoji: "🐅", name: "Tiger" },
         { emoji: "🐆", name: "Leopard" },
         { emoji: "🐴", name: "Horse Face" },
         { emoji: "🐎", name: "Horse" },
         { emoji: "🦄", name: "Unicorn Face" },
         { emoji: "🦓", name: "Zebra" },
         { emoji: "🦌", name: "Deer" },
         { emoji: "🐮", name: "Cow Face" },
         { emoji: "🐂", name: "Ox" },
         { emoji: "🐃", name: "Water Buffalo" },
         { emoji: "🐄", name: "Cow" },
         { emoji: "🐷", name: "Pig Face" },
         { emoji: "🐖", name: "Pig" },
         { emoji: "🐗", name: "Boar" },
         { emoji: "🐽", name: "Pig Nose" },
         { emoji: "🐏", name: "Ram" },
         { emoji: "🐑", name: "Ewe" },
         { emoji: "🐐", name: "Goat" },
         { emoji: "🐪", name: "Camel" },
         { emoji: "🐫", name: "Two-Hump Camel" },
         { emoji: "🦒", name: "Giraffe" },
         { emoji: "🐘", name: "Elephant" },
         { emoji: "🦏", name: "Rhinoceros" },
         { emoji: "🐭", name: "Mouse Face" },
         { emoji: "🐁", name: "Mouse" },
         { emoji: "🐀", name: "Rat" },
         { emoji: "🐹", name: "Hamster Face" },
         { emoji: "🐰", name: "Rabbit Face" },
         { emoji: "🐇", name: "Rabbit" },
         { emoji: "🐿️", name: "Chipmunk" },
         { emoji: "🦔", name: "Hedgehog" },
         { emoji: "🦇", name: "Bat" },
         { emoji: "🐻", name: "Bear Face" },
         { emoji: "🐨", name: "Koala" },
         { emoji: "🐼", name: "Panda Face" },
         { emoji: "🐾", name: "Paw Prints" },
         { emoji: "🦃", name: "Turkey" },
         { emoji: "🐔", name: "Chicken" },
         { emoji: "🐓", name: "Rooster" },
         { emoji: "🐣", name: "Hatching Chick" },
         { emoji: "🐤", name: "Baby Chick" },
         { emoji: "🐥", name: "Front-Facing Baby Chick" },
         { emoji: "🐦", name: "Bird" },
         { emoji: "🐧", name: "Penguin" },
         { emoji: "🕊️", name: "Dove" },
         { emoji: "🦅", name: "Eagle" },
         { emoji: "🦆", name: "Duck" },
         { emoji: "🦉", name: "Owl" },
         { emoji: "🐸", name: "Frog Face" },
         { emoji: "🐊", name: "Crocodile" },
         { emoji: "🐢", name: "Turtle" },
         { emoji: "🦎", name: "Lizard" },
         { emoji: "🐍", name: "Snake" },
         { emoji: "🐲", name: "Dragon Face" },
         { emoji: "🐉", name: "Dragon" },
         { emoji: "🦕", name: "Sauropod" },
         { emoji: "🦖", name: "T-Rex" },
         { emoji: "🐳", name: "Spouting Whale" },
         { emoji: "🐋", name: "Whale" },
         { emoji: "🐬", name: "Dolphin" },
         { emoji: "🐟", name: "Fish" },
         { emoji: "🐠", name: "Tropical Fish" },
         { emoji: "🐡", name: "Blowfish" },
         { emoji: "🦈", name: "Shark" },
         { emoji: "🐙", name: "Octopus" },
         { emoji: "🐚", name: "Spiral Shell" },
         { emoji: "🦀", name: "Crab" },
         { emoji: "🦐", name: "Shrimp" },
         { emoji: "🦑", name: "Squid" },
         { emoji: "🐌", name: "Snail" },
         { emoji: "🦋", name: "Butterfly" },
         { emoji: "🐛", name: "Bug" },
         { emoji: "🐜", name: "Ant" },
         { emoji: "🐝", name: "Honeybee" },
         { emoji: "🐞", name: "Lady Beetle" },
         { emoji: "🦗", name: "Cricket" },
         { emoji: "🕷️", name: "Spider" },
         { emoji: "🕸️", name: "Spider Web" },
         { emoji: "🦂", name: "Scorpion" },
         { emoji: "💐", name: "Bouquet" },
         { emoji: "🌸", name: "Cherry Blossom" },
         { emoji: "💮", name: "White Flower" },
         { emoji: "🏵️", name: "Rosette" },
         { emoji: "🌹", name: "Rose" },
         { emoji: "🥀", name: "Wilted Flower" },
         { emoji: "🌺", name: "Hibiscus" },
         { emoji: "🌻", name: "Sunflower" },
         { emoji: "🌼", name: "Blossom" },
         { emoji: "🌷", name: "Tulip" },
         { emoji: "🌱", name: "Seedling" },
         { emoji: "🌲", name: "Evergreen Tree" },
         { emoji: "🌳", name: "Deciduous Tree" },
         { emoji: "🌴", name: "Palm Tree" },
         { emoji: "🌵", name: "Cactus" },
         { emoji: "🌾", name: "Sheaf Of Rice" },
         { emoji: "🌿", name: "Herb" },
         { emoji: "☘️", name: "Shamrock" },
         { emoji: "🍀", name: "Four Leaf Clover" },
         { emoji: "🍁", name: "Maple Leaf" },
         { emoji: "🍂", name: "Fallen Leaf" },
         { emoji: "🍃", name: "Leaf Fluttering In Wind" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Food & Drink",
      list: [
         { emoji: "🍇", name: "Grapes" },
         { emoji: "🍈", name: "Melon" },
         { emoji: "🍉", name: "Watermelon" },
         { emoji: "🍊", name: "Tangerine" },
         { emoji: "🍋", name: "Lemon" },
         { emoji: "🍌", name: "Banana" },
         { emoji: "🍍", name: "Pineapple" },
         { emoji: "🍎", name: "Red Apple" },
         { emoji: "🍏", name: "Green Apple" },
         { emoji: "🍐", name: "Pear" },
         { emoji: "🍑", name: "Peach" },
         { emoji: "🍒", name: "Cherries" },
         { emoji: "🍓", name: "Strawberry" },
         { emoji: "🥝", name: "Kiwi Fruit" },
         { emoji: "🍅", name: "Tomato" },
         { emoji: "🥥", name: "Coconut" },
         { emoji: "🥑", name: "Avocado" },
         { emoji: "🍆", name: "Eggplant" },
         { emoji: "🥔", name: "Potato" },
         { emoji: "🥕", name: "Carrot" },
         { emoji: "🌽", name: "Ear Of Corn" },
         { emoji: "🌶️", name: "Hot Pepper" },
         { emoji: "🥒", name: "Cucumber" },
         { emoji: "🥦", name: "Broccoli" },
         { emoji: "🍄", name: "Mushroom" },
         { emoji: "🥜", name: "Peanuts" },
         { emoji: "🌰", name: "Chestnut" },
         { emoji: "🍞", name: "Bread" },
         { emoji: "🥐", name: "Croissant" },
         { emoji: "🥖", name: "Baguette Bread" },
         { emoji: "🥨", name: "Pretzel" },
         { emoji: "🥞", name: "Pancakes" },
         { emoji: "🧀", name: "Cheese Wedge" },
         { emoji: "🍖", name: "Meat On Bone" },
         { emoji: "🍗", name: "Poultry Leg" },
         { emoji: "🥩", name: "Cut Of Meat" },
         { emoji: "🥓", name: "Bacon" },
         { emoji: "🍔", name: "Hamburger" },
         { emoji: "🍟", name: "French Fries" },
         { emoji: "🍕", name: "Pizza" },
         { emoji: "🌭", name: "Hot Dog" },
         { emoji: "🥪", name: "Sandwich" },
         { emoji: "🌮", name: "Taco" },
         { emoji: "🌯", name: "Burrito" },
         { emoji: "🥙", name: "Stuffed Flatbread" },
         { emoji: "🥚", name: "Egg" },
         { emoji: "🍳", name: "Cooking" },
         { emoji: "🥘", name: "Shallow Pan Of Food" },
         { emoji: "🍲", name: "Pot Of Food" },
         { emoji: "🥣", name: "Bowl With Spoon" },
         { emoji: "🥗", name: "Green Salad" },
         { emoji: "🍿", name: "Popcorn" },
         { emoji: "🥫", name: "Canned Food" },
         { emoji: "🍱", name: "Bento Box" },
         { emoji: "🍘", name: "Rice Cracker" },
         { emoji: "🍙", name: "Rice Ball" },
         { emoji: "🍚", name: "Cooked Rice" },
         { emoji: "🍛", name: "Curry Rice" },
         { emoji: "🍜", name: "Steaming Bowl" },
         { emoji: "🍝", name: "Spaghetti" },
         { emoji: "🍠", name: "Roasted Sweet Potato" },
         { emoji: "🍢", name: "Oden" },
         { emoji: "🍣", name: "Sushi" },
         { emoji: "🍤", name: "Fried Shrimp" },
         { emoji: "🍥", name: "Fish Cake With Swirl" },
         { emoji: "🍡", name: "Dango" },
         { emoji: "🥟", name: "Dumpling" },
         { emoji: "🥠", name: "Fortune Cookie" },
         { emoji: "🥡", name: "Takeout Box" },
         { emoji: "🍦", name: "Soft Ice Cream" },
         { emoji: "🍧", name: "Shaved Ice" },
         { emoji: "🍨", name: "Ice Cream" },
         { emoji: "🍩", name: "Doughnut" },
         { emoji: "🍪", name: "Cookie" },
         { emoji: "🎂", name: "Birthday Cake" },
         { emoji: "🍰", name: "Shortcake" },
         { emoji: "🥧", name: "Pie" },
         { emoji: "🍫", name: "Chocolate Bar" },
         { emoji: "🍬", name: "Candy" },
         { emoji: "🍭", name: "Lollipop" },
         { emoji: "🍮", name: "Custard" },
         { emoji: "🍯", name: "Honey Pot" },
         { emoji: "🍼", name: "Baby Bottle" },
         { emoji: "🥛", name: "Glass Of Milk" },
         { emoji: "☕", name: "Hot Beverage" },
         { emoji: "🍵", name: "Teacup Without Handle" },
         { emoji: "🍶", name: "Sake" },
         { emoji: "🍾", name: "Bottle With Popping Cork" },
         { emoji: "🍷", name: "Wine Glass" },
         { emoji: "🍸", name: "Cocktail Glass" },
         { emoji: "🍹", name: "Tropical Drink" },
         { emoji: "🍺", name: "Beer Mug" },
         { emoji: "🍻", name: "Clinking Beer Mugs" },
         { emoji: "🥂", name: "Clinking Glasses" },
         { emoji: "🥃", name: "Tumbler Glass" },
         { emoji: "🥤", name: "Cup With Straw" },
         { emoji: "🥢", name: "Chopsticks" },
         { emoji: "🍽️", name: "Fork And Knife With Plate" },
         { emoji: "🍴", name: "Fork And Knife" },
         { emoji: "🥄", name: "Spoon" },
         { emoji: "🔪", name: "Kitchen Knife" },
         { emoji: "🏺", name: "Amphora" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Travel & Places",
      list: [
         { emoji: "🌍", name: "Globe Showing Europe-Africa" },
         { emoji: "🌎", name: "Globe Showing Americas" },
         { emoji: "🌏", name: "Globe Showing Asia-Australia" },
         { emoji: "🌐", name: "Globe With Meridians" },
         { emoji: "🗺️", name: "World Map" },
         { emoji: "🗾", name: "Map Of Japan" },
         { emoji: "🏔️", name: "Snow-Capped Mountain" },
         { emoji: "⛰️", name: "Mountain" },
         { emoji: "🌋", name: "Volcano" },
         { emoji: "🗻", name: "Mount Fuji" },
         { emoji: "🏕️", name: "Camping" },
         { emoji: "🏖️", name: "Beach With Umbrella" },
         { emoji: "🏜️", name: "Desert" },
         { emoji: "🏝️", name: "Desert Island" },
         { emoji: "🏞️", name: "National Park" },
         { emoji: "🏟️", name: "Stadium" },
         { emoji: "🏛️", name: "Classical Building" },
         { emoji: "🏗️", name: "Building Construction" },
         { emoji: "🏘️", name: "Houses" },
         { emoji: "🏚️", name: "Derelict House" },
         { emoji: "🏠", name: "House" },
         { emoji: "🏡", name: "House With Garden" },
         { emoji: "🏢", name: "Office Building" },
         { emoji: "🏣", name: "Japanese Post Office" },
         { emoji: "🏤", name: "Post Office" },
         { emoji: "🏥", name: "Hospital" },
         { emoji: "🏦", name: "Bank" },
         { emoji: "🏨", name: "Hotel" },
         { emoji: "🏩", name: "Love Hotel" },
         { emoji: "🏪", name: "Convenience Store" },
         { emoji: "🏫", name: "School" },
         { emoji: "🏬", name: "Department Store" },
         { emoji: "🏭", name: "Factory" },
         { emoji: "🏯", name: "Japanese Castle" },
         { emoji: "🏰", name: "Castle" },
         { emoji: "💒", name: "Wedding" },
         { emoji: "🗼", name: "Tokyo Tower" },
         { emoji: "🗽", name: "Statue Of Liberty" },
         { emoji: "⛪", name: "Church" },
         { emoji: "🕌", name: "Mosque" },
         { emoji: "🕍", name: "Synagogue" },
         { emoji: "⛩️", name: "Shinto Shrine" },
         { emoji: "🕋", name: "Kaaba" },
         { emoji: "⛲", name: "Fountain" },
         { emoji: "⛺", name: "Tent" },
         { emoji: "🌁", name: "Foggy" },
         { emoji: "🌃", name: "Night With Stars" },
         { emoji: "🏙️", name: "Cityscape" },
         { emoji: "🌄", name: "Sunrise Over Mountains" },
         { emoji: "🌅", name: "Sunrise" },
         { emoji: "🌆", name: "Cityscape At Dusk" },
         { emoji: "🌇", name: "Sunset" },
         { emoji: "🌉", name: "Bridge At Night" },
         { emoji: "♨️", name: "Hot Springs" },
         { emoji: "🌌", name: "Milky Way" },
         { emoji: "🎠", name: "Carousel Horse" },
         { emoji: "🎡", name: "Ferris Wheel" },
         { emoji: "🎢", name: "Roller Coaster" },
         { emoji: "💈", name: "Barber Pole" },
         { emoji: "🎪", name: "Circus Tent" },
         { emoji: "🚂", name: "Locomotive" },
         { emoji: "🚃", name: "Railway Car" },
         { emoji: "🚄", name: "High-Speed Train" },
         { emoji: "🚅", name: "Bullet Train" },
         { emoji: "🚆", name: "Train" },
         { emoji: "🚇", name: "Metro" },
         { emoji: "🚈", name: "Light Rail" },
         { emoji: "🚉", name: "Station" },
         { emoji: "🚊", name: "Tram" },
         { emoji: "🚝", name: "Monorail" },
         { emoji: "🚞", name: "Mountain Railway" },
         { emoji: "🚋", name: "Tram Car" },
         { emoji: "🚌", name: "Bus" },
         { emoji: "🚍", name: "Oncoming Bus" },
         { emoji: "🚎", name: "Trolleybus" },
         { emoji: "🚐", name: "Minibus" },
         { emoji: "🚑", name: "Ambulance" },
         { emoji: "🚒", name: "Fire Engine" },
         { emoji: "🚓", name: "Police Car" },
         { emoji: "🚔", name: "Oncoming Police Car" },
         { emoji: "🚕", name: "Taxi" },
         { emoji: "🚖", name: "Oncoming Taxi" },
         { emoji: "🚗", name: "Automobile" },
         { emoji: "🚘", name: "Oncoming Automobile" },
         { emoji: "🚙", name: "Sport Utility Vehicle" },
         { emoji: "🚚", name: "Delivery Truck" },
         { emoji: "🚛", name: "Articulated Lorry" },
         { emoji: "🚜", name: "Tractor" },
         { emoji: "🚲", name: "Bicycle" },
         { emoji: "🛴", name: "Kick Scooter" },
         { emoji: "🛵", name: "Motor Scooter" },
         { emoji: "🚏", name: "Bus Stop" },
         { emoji: "🛣️", name: "Motorway" },
         { emoji: "🛤️", name: "Railway Track" },
         { emoji: "🛢️", name: "Oil Drum" },
         { emoji: "⛽", name: "Fuel Pump" },
         { emoji: "🚨", name: "Police Car Light" },
         { emoji: "🚥", name: "Horizontal Traffic Light" },
         { emoji: "🚦", name: "Vertical Traffic Light" },
         { emoji: "🛑", name: "Stop Sign" },
         { emoji: "🚧", name: "Construction" },
         { emoji: "⚓", name: "Anchor" },
         { emoji: "⛵", name: "Sailboat" },
         { emoji: "🛶", name: "Canoe" },
         { emoji: "🚤", name: "Speedboat" },
         { emoji: "🛳️", name: "Passenger Ship" },
         { emoji: "⛴️", name: "Ferry" },
         { emoji: "🛥️", name: "Motor Boat" },
         { emoji: "🚢", name: "Ship" },
         { emoji: "✈️", name: "Airplane" },
         { emoji: "🛩️", name: "Small Airplane" },
         { emoji: "🛫", name: "Airplane Departure" },
         { emoji: "🛬", name: "Airplane Arrival" },
         { emoji: "💺", name: "Seat" },
         { emoji: "🚁", name: "Helicopter" },
         { emoji: "🚟", name: "Suspension Railway" },
         { emoji: "🚠", name: "Mountain Cableway" },
         { emoji: "🚡", name: "Aerial Tramway" },
         { emoji: "🛰️", name: "Satellite" },
         { emoji: "🚀", name: "Rocket" },
         { emoji: "🛸", name: "Flying Saucer" },
         { emoji: "🛎️", name: "Bellhop Bell" },
         { emoji: "⌛", name: "Hourglass Done" },
         { emoji: "⏳", name: "Hourglass Not Done" },
         { emoji: "⌚", name: "Watch" },
         { emoji: "⏰", name: "Alarm Clock" },
         { emoji: "⏱️", name: "Stopwatch" },
         { emoji: "⏲️", name: "Timer Clock" },
         { emoji: "🕰️", name: "Mantelpiece Clock" },
         { emoji: "🕛", name: "Twelve O’Clock" },
         { emoji: "🕧", name: "Twelve-Thirty" },
         { emoji: "🕐", name: "One O’Clock" },
         { emoji: "🕜", name: "One-Thirty" },
         { emoji: "🕑", name: "Two O’Clock" },
         { emoji: "🕝", name: "Two-Thirty" },
         { emoji: "🕒", name: "Three O’Clock" },
         { emoji: "🕞", name: "Three-Thirty" },
         { emoji: "🕓", name: "Four O’Clock" },
         { emoji: "🕟", name: "Four-Thirty" },
         { emoji: "🕔", name: "Five O’Clock" },
         { emoji: "🕠", name: "Five-Thirty" },
         { emoji: "🕕", name: "Six O’Clock" },
         { emoji: "🕡", name: "Six-Thirty" },
         { emoji: "🕖", name: "Seven O’Clock" },
         { emoji: "🕢", name: "Seven-Thirty" },
         { emoji: "🕗", name: "Eight O’Clock" },
         { emoji: "🕣", name: "Eight-Thirty" },
         { emoji: "🕘", name: "Nine O’Clock" },
         { emoji: "🕤", name: "Nine-Thirty" },
         { emoji: "🕙", name: "Ten O’Clock" },
         { emoji: "🕥", name: "Ten-Thirty" },
         { emoji: "🕚", name: "Eleven O’Clock" },
         { emoji: "🕦", name: "Eleven-Thirty" },
         { emoji: "🌑", name: "New Moon" },
         { emoji: "🌒", name: "Waxing Crescent Moon" },
         { emoji: "🌓", name: "First Quarter Moon" },
         { emoji: "🌔", name: "Waxing Gibbous Moon" },
         { emoji: "🌕", name: "Full Moon" },
         { emoji: "🌖", name: "Waning Gibbous Moon" },
         { emoji: "🌗", name: "Last Quarter Moon" },
         { emoji: "🌘", name: "Waning Crescent Moon" },
         { emoji: "🌙", name: "Crescent Moon" },
         { emoji: "🌚", name: "New Moon Face" },
         { emoji: "🌛", name: "First Quarter Moon Face" },
         { emoji: "🌜", name: "Last Quarter Moon Face" },
         { emoji: "🌡️", name: "Thermometer" },
         { emoji: "☀️", name: "Sun" },
         { emoji: "🌝", name: "Full Moon Face" },
         { emoji: "🌞", name: "Sun With Face" },
         { emoji: "⭐", name: "Star" },
         { emoji: "🌟", name: "Glowing Star" },
         { emoji: "🌠", name: "Shooting Star" },
         { emoji: "☁️", name: "Cloud" },
         { emoji: "⛅", name: "Sun Behind Cloud" },
         { emoji: "⛈️", name: "Cloud With Lightning And Rain" },
         { emoji: "🌤️", name: "Sun Behind Small Cloud" },
         { emoji: "🌥️", name: "Sun Behind Large Cloud" },
         { emoji: "🌦️", name: "Sun Behind Rain Cloud" },
         { emoji: "🌧️", name: "Cloud With Rain" },
         { emoji: "🌨️", name: "Cloud With Snow" },
         { emoji: "🌩️", name: "Cloud With Lightning" },
         { emoji: "🌪️", name: "Tornado" },
         { emoji: "🌫️", name: "Fog" },
         { emoji: "🌬️", name: "Wind Face" },
         { emoji: "🌀", name: "Cyclone" },
         { emoji: "🌈", name: "Rainbow" },
         { emoji: "🌂", name: "Closed Umbrella" },
         { emoji: "☂️", name: "Umbrella" },
         { emoji: "☔", name: "Umbrella With Rain Drops" },
         { emoji: "⛱️", name: "Umbrella On Ground" },
         { emoji: "⚡", name: "High Voltage" },
         { emoji: "❄️", name: "Snowflake" },
         { emoji: "☃️", name: "Snowman" },
         { emoji: "⛄", name: "Snowman Without Snow" },
         { emoji: "☄️", name: "Comet" },
         { emoji: "🔥", name: "Fire" },
         { emoji: "💧", name: "Droplet" },
         { emoji: "🌊", name: "Water Wave" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Activities",
      list: [
         { emoji: "🎃", name: "Jack-O-Lantern" },
         { emoji: "🎄", name: "Christmas Tree" },
         { emoji: "🎆", name: "Fireworks" },
         { emoji: "🎇", name: "Sparkler" },
         { emoji: "✨", name: "Sparkles" },
         { emoji: "🎈", name: "Balloon" },
         { emoji: "🎉", name: "Party Popper" },
         { emoji: "🎊", name: "Confetti Ball" },
         { emoji: "🎋", name: "Tanabata Tree" },
         { emoji: "🎍", name: "Pine Decoration" },
         { emoji: "🎎", name: "Japanese Dolls" },
         { emoji: "🎏", name: "Carp Streamer" },
         { emoji: "🎐", name: "Wind Chime" },
         { emoji: "🎑", name: "Moon Viewing Ceremony" },
         { emoji: "🎀", name: "Ribbon" },
         { emoji: "🎁", name: "Wrapped Gift" },
         { emoji: "🎗️", name: "Reminder Ribbon" },
         { emoji: "🎟️", name: "Admission Tickets" },
         { emoji: "🎫", name: "Ticket" },
         { emoji: "🎖️", name: "Military Medal" },
         { emoji: "🏆", name: "Trophy" },
         { emoji: "🏅", name: "Sports Medal" },
         { emoji: "🥇", name: "1St Place Medal" },
         { emoji: "🥈", name: "2Nd Place Medal" },
         { emoji: "🥉", name: "3Rd Place Medal" },
         { emoji: "⚽", name: "Soccer Ball" },
         { emoji: "⚾", name: "Baseball" },
         { emoji: "🏀", name: "Basketball" },
         { emoji: "🏐", name: "Volleyball" },
         { emoji: "🏈", name: "American Football" },
         { emoji: "🏉", name: "Rugby Football" },
         { emoji: "🎾", name: "Tennis" },
         { emoji: "🎳", name: "Bowling" },
         { emoji: "🏏", name: "Cricket Game" },
         { emoji: "🏑", name: "Field Hockey" },
         { emoji: "🏒", name: "Ice Hockey" },
         { emoji: "🏓", name: "Ping Pong" },
         { emoji: "🏸", name: "Badminton" },
         { emoji: "🥊", name: "Boxing Glove" },
         { emoji: "🥋", name: "Martial Arts Uniform" },
         { emoji: "🥅", name: "Goal Net" },
         { emoji: "⛳", name: "Flag In Hole" },
         { emoji: "⛸️", name: "Ice Skate" },
         { emoji: "🎣", name: "Fishing Pole" },
         { emoji: "🎽", name: "Running Shirt" },
         { emoji: "🎿", name: "Skis" },
         { emoji: "🛷", name: "Sled" },
         { emoji: "🥌", name: "Curling Stone" },
         { emoji: "🎯", name: "Direct Hit" },
         { emoji: "🎱", name: "Pool 8 Ball" },
         { emoji: "🔮", name: "Crystal Ball" },
         { emoji: "🎮", name: "Video Game" },
         { emoji: "🕹️", name: "Joystick" },
         { emoji: "🎰", name: "Slot Machine" },
         { emoji: "🎲", name: "Game Die" },
         { emoji: "♠️", name: "Spade Suit" },
         { emoji: "♥️", name: "Heart Suit" },
         { emoji: "♦️", name: "Diamond Suit" },
         { emoji: "♣️", name: "Club Suit" },
         { emoji: "♟️", name: "Chess Pawn" },
         { emoji: "🃏", name: "Joker" },
         { emoji: "🀄", name: "Mahjong Red Dragon" },
         { emoji: "🎴", name: "Flower Playing Cards" },
         { emoji: "🎭", name: "Performing Arts" },
         { emoji: "🖼️", name: "Framed Picture" },
         { emoji: "🎨", name: "Artist Palette" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Objects",
      list: [
         { emoji: "🔇", name: "Muted Speaker" },
         { emoji: "🔈", name: "Speaker Low Volume" },
         { emoji: "🔉", name: "Speaker Medium Volume" },
         { emoji: "🔊", name: "Speaker High Volume" },
         { emoji: "📢", name: "Loudspeaker" },
         { emoji: "📣", name: "Megaphone" },
         { emoji: "📯", name: "Postal Horn" },
         { emoji: "🔔", name: "Bell" },
         { emoji: "🔕", name: "Bell With Slash" },
         { emoji: "🎼", name: "Musical Score" },
         { emoji: "🎵", name: "Musical Note" },
         { emoji: "🎶", name: "Musical Notes" },
         { emoji: "🎙️", name: "Studio Microphone" },
         { emoji: "🎚️", name: "Level Slider" },
         { emoji: "🎛️", name: "Control Knobs" },
         { emoji: "🎤", name: "Microphone" },
         { emoji: "🎧", name: "Headphone" },
         { emoji: "📻", name: "Radio" },
         { emoji: "🎷", name: "Saxophone" },
         { emoji: "🎸", name: "Guitar" },
         { emoji: "🎹", name: "Musical Keyboard" },
         { emoji: "🎺", name: "Trumpet" },
         { emoji: "🎻", name: "Violin" },
         { emoji: "🥁", name: "Drum" },
         { emoji: "📱", name: "Mobile Phone" },
         { emoji: "📲", name: "Mobile Phone With Arrow" },
         { emoji: "☎️", name: "Telephone" },
         { emoji: "📞", name: "Telephone Receiver" },
         { emoji: "📟", name: "Pager" },
         { emoji: "📠", name: "Fax Machine" },
         { emoji: "🔋", name: "Battery" },
         { emoji: "🔌", name: "Electric Plug" },
         { emoji: "💻", name: "Laptop Computer" },
         { emoji: "🖥️", name: "Desktop Computer" },
         { emoji: "🖨️", name: "Printer" },
         { emoji: "⌨️", name: "Keyboard" },
         { emoji: "🖱️", name: "Computer Mouse" },
         { emoji: "🖲️", name: "Trackball" },
         { emoji: "💽", name: "Computer Disk" },
         { emoji: "💾", name: "Floppy Disk" },
         { emoji: "💿", name: "Optical Disk" },
         { emoji: "📀", name: "Dvd" },
         { emoji: "🎥", name: "Movie Camera" },
         { emoji: "🎞️", name: "Film Frames" },
         { emoji: "📽️", name: "Film Projector" },
         { emoji: "🎬", name: "Clapper Board" },
         { emoji: "📺", name: "Television" },
         { emoji: "📷", name: "Camera" },
         { emoji: "📸", name: "Camera With Flash" },
         { emoji: "📹", name: "Video Camera" },
         { emoji: "📼", name: "Videocassette" },
         { emoji: "🔍", name: "Magnifying Glass Tilted Left" },
         { emoji: "🔎", name: "Magnifying Glass Tilted Right" },
         { emoji: "🕯️", name: "Candle" },
         { emoji: "💡", name: "Light Bulb" },
         { emoji: "🔦", name: "Flashlight" },
         { emoji: "🏮", name: "Red Paper Lantern" },
         { emoji: "📔", name: "Notebook With Decorative Cover" },
         { emoji: "📕", name: "Closed Book" },
         { emoji: "📖", name: "Open Book" },
         { emoji: "📗", name: "Green Book" },
         { emoji: "📘", name: "Blue Book" },
         { emoji: "📙", name: "Orange Book" },
         { emoji: "📚", name: "Books" },
         { emoji: "📓", name: "Notebook" },
         { emoji: "📒", name: "Ledger" },
         { emoji: "📃", name: "Page With Curl" },
         { emoji: "📜", name: "Scroll" },
         { emoji: "📄", name: "Page Facing Up" },
         { emoji: "📰", name: "Newspaper" },
         { emoji: "🗞️", name: "Rolled-Up Newspaper" },
         { emoji: "📑", name: "Bookmark Tabs" },
         { emoji: "🔖", name: "Bookmark" },
         { emoji: "🏷️", name: "Label" },
         { emoji: "💰", name: "Money Bag" },
         { emoji: "💴", name: "Yen Banknote" },
         { emoji: "💵", name: "Dollar Banknote" },
         { emoji: "💶", name: "Euro Banknote" },
         { emoji: "💷", name: "Pound Banknote" },
         { emoji: "💸", name: "Money With Wings" },
         { emoji: "💳", name: "Credit Card" },
         { emoji: "💹", name: "Chart Increasing With Yen" },
         { emoji: "💱", name: "Currency Exchange" },
         { emoji: "💲", name: "Heavy Dollar Sign" },
         { emoji: "✉️", name: "Envelope" },
         { emoji: "📧", name: "E-Mail" },
         { emoji: "📨", name: "Incoming Envelope" },
         { emoji: "📩", name: "Envelope With Arrow" },
         { emoji: "📤", name: "Outbox Tray" },
         { emoji: "📥", name: "Inbox Tray" },
         { emoji: "📦", name: "Package" },
         { emoji: "📫", name: "Closed Mailbox With Raised Flag" },
         { emoji: "📪", name: "Closed Mailbox With Lowered Flag" },
         { emoji: "📬", name: "Open Mailbox With Raised Flag" },
         { emoji: "📭", name: "Open Mailbox With Lowered Flag" },
         { emoji: "📮", name: "Postbox" },
         { emoji: "🗳️", name: "Ballot Box With Ballot" },
         { emoji: "✏️", name: "Pencil" },
         { emoji: "✒️", name: "Black Nib" },
         { emoji: "🖋️", name: "Fountain Pen" },
         { emoji: "🖊️", name: "Pen" },
         { emoji: "🖌️", name: "Paintbrush" },
         { emoji: "🖍️", name: "Crayon" },
         { emoji: "📝", name: "Memo" },
         { emoji: "💼", name: "Briefcase" },
         { emoji: "📁", name: "File Folder" },
         { emoji: "📂", name: "Open File Folder" },
         { emoji: "🗂️", name: "Card Index Dividers" },
         { emoji: "📅", name: "Calendar" },
         { emoji: "📆", name: "Tear-Off Calendar" },
         { emoji: "🗒️", name: "Spiral Notepad" },
         { emoji: "🗓️", name: "Spiral Calendar" },
         { emoji: "📇", name: "Card Index" },
         { emoji: "📈", name: "Chart Increasing" },
         { emoji: "📉", name: "Chart Decreasing" },
         { emoji: "📊", name: "Bar Chart" },
         { emoji: "📋", name: "Clipboard" },
         { emoji: "📌", name: "Pushpin" },
         { emoji: "📍", name: "Round Pushpin" },
         { emoji: "📎", name: "Paperclip" },
         { emoji: "🖇️", name: "Linked Paperclips" },
         { emoji: "📏", name: "Straight Ruler" },
         { emoji: "📐", name: "Triangular Ruler" },
         { emoji: "✂️", name: "Scissors" },
         { emoji: "🗃️", name: "Card File Box" },
         { emoji: "🗄️", name: "File Cabinet" },
         { emoji: "🗑️", name: "Wastebasket" },
         { emoji: "🔒", name: "Locked" },
         { emoji: "🔓", name: "Unlocked" },
         { emoji: "🔏", name: "Locked With Pen" },
         { emoji: "🔐", name: "Locked With Key" },
         { emoji: "🔑", name: "Key" },
         { emoji: "🗝️", name: "Old Key" },
         { emoji: "🔨", name: "Hammer" },
         { emoji: "⛏️", name: "Pick" },
         { emoji: "⚒️", name: "Hammer And Pick" },
         { emoji: "🛠️", name: "Hammer And Wrench" },
         { emoji: "🗡️", name: "Dagger" },
         { emoji: "⚔️", name: "Crossed Swords" },
         { emoji: "🔫", name: "Pistol" },
         { emoji: "🏹", name: "Bow And Arrow" },
         { emoji: "🛡️", name: "Shield" },
         { emoji: "🔧", name: "Wrench" },
         { emoji: "🔩", name: "Nut And Bolt" },
         { emoji: "⚙️", name: "Gear" },
         { emoji: "🗜️", name: "Clamp" },
         { emoji: "⚖️", name: "Balance Scale" },
         { emoji: "🔗", name: "Link" },
         { emoji: "⛓️", name: "Chains" },
         { emoji: "⚗️", name: "Alembic" },
         { emoji: "🔬", name: "Microscope" },
         { emoji: "🔭", name: "Telescope" },
         { emoji: "📡", name: "Satellite Antenna" },
         { emoji: "💉", name: "Syringe" },
         { emoji: "💊", name: "Pill" },
         { emoji: "🚪", name: "Door" },
         { emoji: "🛏️", name: "Bed" },
         { emoji: "🛋️", name: "Couch And Lamp" },
         { emoji: "🚽", name: "Toilet" },
         { emoji: "🚿", name: "Shower" },
         { emoji: "🛁", name: "Bathtub" },
         { emoji: "🛒", name: "Shopping Cart" },
         { emoji: "🚬", name: "Cigarette" },
         { emoji: "⚰️", name: "Coffin" },
         { emoji: "⚱️", name: "Funeral Urn" },
         { emoji: "🗿", name: "Moai" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Symbols",
      list: [
         { emoji: "🏧", name: "Atm Sign" },
         { emoji: "🚮", name: "Litter In Bin Sign" },
         { emoji: "🚰", name: "Potable Water" },
         { emoji: "♿", name: "Wheelchair Symbol" },
         { emoji: "🚹", name: "Men's Room" },
         { emoji: "🚺", name: "Women's Room" },
         { emoji: "🚻", name: "Restroom" },
         { emoji: "🚼", name: "Baby Symbol" },
         { emoji: "🚾", name: "Water Closet" },
         { emoji: "🛂", name: "Passport Control" },
         { emoji: "🛃", name: "Customs" },
         { emoji: "🛄", name: "Baggage Claim" },
         { emoji: "🛅", name: "Left Luggage" },
         { emoji: "⚠️", name: "Warning" },
         { emoji: "🚸", name: "Children Crossing" },
         { emoji: "⛔", name: "No Entry" },
         { emoji: "🚫", name: "Prohibited" },
         { emoji: "🚳", name: "No Bicycles" },
         { emoji: "🚭", name: "No Smoking" },
         { emoji: "🚯", name: "No Littering" },
         { emoji: "🚱", name: "Non-Potable Water" },
         { emoji: "🚷", name: "No Pedestrians" },
         { emoji: "📵", name: "No Mobile Phones" },
         { emoji: "🔞", name: "No One Under Eighteen" },
         { emoji: "☢️", name: "Radioactive" },
         { emoji: "☣️", name: "Biohazard" },
         { emoji: "⬆️", name: "Up Arrow" },
         { emoji: "↗️", name: "Up-Right Arrow" },
         { emoji: "➡️", name: "Right Arrow" },
         { emoji: "↘️", name: "Down-Right Arrow" },
         { emoji: "⬇️", name: "Down Arrow" },
         { emoji: "↙️", name: "Down-Left Arrow" },
         { emoji: "⬅️", name: "Left Arrow" },
         { emoji: "↖️", name: "Up-Left Arrow" },
         { emoji: "↕️", name: "Up-Down Arrow" },
         { emoji: "↔️", name: "Left-Right Arrow" },
         { emoji: "↩️", name: "Right Arrow Curving Left" },
         { emoji: "↪️", name: "Left Arrow Curving Right" },
         { emoji: "⤴️", name: "Right Arrow Curving Up" },
         { emoji: "⤵️", name: "Right Arrow Curving Down" },
         { emoji: "🔃", name: "Clockwise Vertical Arrows" },
         { emoji: "🔄", name: "Counterclockwise Arrows Button" },
         { emoji: "🔙", name: "Back Arrow" },
         { emoji: "🔚", name: "End Arrow" },
         { emoji: "🔛", name: "On! Arrow" },
         { emoji: "🔜", name: "Soon Arrow" },
         { emoji: "🔝", name: "Top Arrow" },
         { emoji: "🛐", name: "Place Of Worship" },
         { emoji: "⚛️", name: "Atom Symbol" },
         { emoji: "🕉️", name: "Om" },
         { emoji: "✡️", name: "Star Of David" },
         { emoji: "☸️", name: "Wheel Of Dharma" },
         { emoji: "☯️", name: "Yin Yang" },
         { emoji: "✝️", name: "Latin Cross" },
         { emoji: "☦️", name: "Orthodox Cross" },
         { emoji: "☪️", name: "Star And Crescent" },
         { emoji: "☮️", name: "Peace Symbol" },
         { emoji: "🕎", name: "Menorah" },
         { emoji: "🔯", name: "Dotted Six-Pointed Star" },
         { emoji: "♈", name: "Aries" },
         { emoji: "♉", name: "Taurus" },
         { emoji: "♊", name: "Gemini" },
         { emoji: "♋", name: "Cancer" },
         { emoji: "♌", name: "Leo" },
         { emoji: "♍", name: "Virgo" },
         { emoji: "♎", name: "Libra" },
         { emoji: "♏", name: "Scorpio" },
         { emoji: "♐", name: "Sagittarius" },
         { emoji: "♑", name: "Capricorn" },
         { emoji: "♒", name: "Aquarius" },
         { emoji: "♓", name: "Pisces" },
         { emoji: "⛎", name: "Ophiuchus" },
         { emoji: "🔀", name: "Shuffle Tracks Button" },
         { emoji: "🔁", name: "Repeat Button" },
         { emoji: "🔂", name: "Repeat Single Button" },
         { emoji: "▶️", name: "Play Button" },
         { emoji: "⏩", name: "Fast-Forward Button" },
         { emoji: "⏭️", name: "Next Track Button" },
         { emoji: "⏯️", name: "Play Or Pause Button" },
         { emoji: "◀️", name: "Reverse Button" },
         { emoji: "⏪", name: "Fast Reverse Button" },
         { emoji: "⏮️", name: "Last Track Button" },
         { emoji: "🔼", name: "Upwards Button" },
         { emoji: "⏫", name: "Fast Up Button" },
         { emoji: "🔽", name: "Downwards Button" },
         { emoji: "⏬", name: "Fast Down Button" },
         { emoji: "⏸️", name: "Pause Button" },
         { emoji: "⏹️", name: "Stop Button" },
         { emoji: "⏺️", name: "Record Button" },
         { emoji: "⏏️", name: "Eject Button" },
         { emoji: "🎦", name: "Cinema" },
         { emoji: "🔅", name: "Dim Button" },
         { emoji: "🔆", name: "Bright Button" },
         { emoji: "📶", name: "Antenna Bars" },
         { emoji: "📳", name: "Vibration Mode" },
         { emoji: "📴", name: "Mobile Phone Off" },
         { emoji: "♀️", name: "Female Sign" },
         { emoji: "♂️", name: "Male Sign" },
         { emoji: "⚕️", name: "Medical Symbol" },
         { emoji: "♾️", name: "Infinity" },
         { emoji: "♻️", name: "Recycling Symbol" },
         { emoji: "⚜️", name: "Fleur-De-Lis" },
         { emoji: "🔱", name: "Trident Emblem" },
         { emoji: "📛", name: "Name Badge" },
         { emoji: "🔰", name: "Japanese Symbol For Beginner" },
         { emoji: "⭕", name: "Heavy Large Circle" },
         { emoji: "✅", name: "White Heavy Check Mark" },
         { emoji: "☑️", name: "Ballot Box With Check" },
         { emoji: "✔️", name: "Heavy Check Mark" },
         { emoji: "✖️", name: "Heavy Multiplication X" },
         { emoji: "❌", name: "Cross Mark" },
         { emoji: "❎", name: "Cross Mark Button" },
         { emoji: "➕", name: "Heavy Plus Sign" },
         { emoji: "➖", name: "Heavy Minus Sign" },
         { emoji: "➗", name: "Heavy Division Sign" },
         { emoji: "➰", name: "Curly Loop" },
         { emoji: "➿", name: "Double Curly Loop" },
         { emoji: "〽️", name: "Part Alternation Mark" },
         { emoji: "✳️", name: "Eight-Spoked Asterisk" },
         { emoji: "✴️", name: "Eight-Pointed Star" },
         { emoji: "❇️", name: "Sparkle" },
         { emoji: "‼️", name: "Double Exclamation Mark" },
         { emoji: "⁉️", name: "Exclamation Question Mark" },
         { emoji: "❓", name: "Question Mark" },
         { emoji: "❔", name: "White Question Mark" },
         { emoji: "❕", name: "White Exclamation Mark" },
         { emoji: "❗", name: "Exclamation Mark" },
         { emoji: "〰️", name: "Wavy Dash" },
         { emoji: "©️", name: "Copyright" },
         { emoji: "®️", name: "Registered" },
         { emoji: "™️", name: "Trade Mark" },
         { emoji: "#️⃣", name: "Keycap: #" },
         { emoji: "*️⃣", name: "Keycap: *" },
         { emoji: "0️⃣", name: "Keycap: 0" },
         { emoji: "1️⃣", name: "Keycap: 1" },
         { emoji: "2️⃣", name: "Keycap: 2" },
         { emoji: "3️⃣", name: "Keycap: 3" },
         { emoji: "4️⃣", name: "Keycap: 4" },
         { emoji: "5️⃣", name: "Keycap: 5" },
         { emoji: "6️⃣", name: "Keycap: 6" },
         { emoji: "7️⃣", name: "Keycap: 7" },
         { emoji: "8️⃣", name: "Keycap: 8" },
         { emoji: "9️⃣", name: "Keycap: 9" },
         { emoji: "🔟", name: "Keycap: 10" },
         { emoji: "💯", name: "Hundred Points" },
         { emoji: "🔠", name: "Input Latin Uppercase" },
         { emoji: "🔡", name: "Input Latin Lowercase" },
         { emoji: "🔢", name: "Input Numbers" },
         { emoji: "🔣", name: "Input Symbols" },
         { emoji: "🔤", name: "Input Latin Letters" },
         { emoji: "🅰️", name: "A Button (Blood Type)" },
         { emoji: "🆎", name: "Ab Button (Blood Type)" },
         { emoji: "🅱️", name: "B Button (Blood Type)" },
         { emoji: "🆑", name: "Cl Button" },
         { emoji: "🆒", name: "Cool Button" },
         { emoji: "🆓", name: "Free Button" },
         { emoji: "ℹ️", name: "Information" },
         { emoji: "🆔", name: "Id Button" },
      ],
   },
   {
      title: "Circled",
      list: [
         { emoji: "🆕", name: "New Button" },
         { emoji: "🆖", name: "Ng Button" },
         { emoji: "🅾️", name: "O Button (Blood Type)" },
         { emoji: "🆗", name: "Ok Button" },
         { emoji: "🅿️", name: "P Button" },
         { emoji: "🆘", name: "Sos Button" },
         { emoji: "🆙", name: "Up! Button" },
         { emoji: "🆚", name: "Vs Button" },
         { emoji: "🈁", name: "Japanese “Here” Button" },
         { emoji: "🈂️", name: "Japanese “Service Charge” Button" },
         { emoji: "🈷️", name: "Japanese “Monthly Amount” Button" },
         { emoji: "🈶", name: "Japanese “Not Free Of Charge” Button" },
         { emoji: "🈯", name: "Japanese “Reserved” Button" },
         { emoji: "🉐", name: "Japanese “Bargain” Button" },
         { emoji: "🈹", name: "Japanese “Discount” Button" },
         { emoji: "🈚", name: "Japanese “Free Of Charge” Button" },
         { emoji: "🈲", name: "Japanese “Prohibited” Button" },
         { emoji: "🉑", name: "Japanese “Acceptable” Button" },
         { emoji: "🈸", name: "Japanese “Application” Button" },
         { emoji: "🈴", name: "Japanese “Passing Grade” Button" },
         { emoji: "🈳", name: "Japanese “Vacancy” Button" },
         { emoji: "㊗️", name: "Japanese “Congratulations” Button" },
         { emoji: "㊙️", name: "Japanese “Secret” Button" },
         { emoji: "🈺", name: "Japanese “Open For Business” Button" },
         { emoji: "🈵", name: "Japanese “No Vacancy” Button" },
         { emoji: "▪️", name: "Black Small Square" },
         { emoji: "▫️", name: "White Small Square" },
         { emoji: "◻️", name: "White Medium Square" },
         { emoji: "◼️", name: "Black Medium Square" },
         { emoji: "◽", name: "White Medium-Small Square" },
         { emoji: "◾", name: "Black Medium-Small Square" },
         { emoji: "⬛", name: "Black Large Square" },
         { emoji: "⬜", name: "White Large Square" },
         { emoji: "🔶", name: "Large Orange Diamond" },
         { emoji: "🔷", name: "Large Blue Diamond" },
         { emoji: "🔸", name: "Small Orange Diamond" },
         { emoji: "🔹", name: "Small Blue Diamond" },
         { emoji: "🔺", name: "Red Triangle Pointed Up" },
         { emoji: "🔻", name: "Red Triangle Pointed Down" },
         { emoji: "💠", name: "Diamond With A Dot" },
         { emoji: "🔘", name: "Radio Button" },
         { emoji: "🔲", name: "Black Square Button" },
         { emoji: "🔳", name: "White Square Button" },
         { emoji: "⚪", name: "White Circle" },
         { emoji: "⚫", name: "Black Circle" },
         { emoji: "🔴", name: "Red Circle" },
         { emoji: "🔵", name: "Blue Circle" },
      ],
   },
   { title: "", list: [] },
   {
      title: "Flags",
      list: [
         { emoji: "🏁", name: "Chequered Flag" },
         { emoji: "🚩", name: "Triangular Flag" },
         { emoji: "🎌", name: "Crossed Flags" },
         { emoji: "🏴", name: "Black Flag" },
         { emoji: "🏳️", name: "White Flag" },
         { emoji: "🏳️\u200d🌈", name: "Rainbow Flag" },
         { emoji: "🏴\u200d☠️", name: "Pirate Flag" },
         { emoji: "🇦🇨", name: "Ascension Island" },
         { emoji: "🇦🇩", name: "Andorra" },
         { emoji: "🇦🇪", name: "United Arab Emirates" },
         { emoji: "🇦🇫", name: "Afghanistan" },
         { emoji: "🇦🇬", name: "Antigua & Barbuda" },
         { emoji: "🇦🇮", name: "Anguilla" },
         { emoji: "🇦🇱", name: "Albania" },
         { emoji: "🇦🇲", name: "Armenia" },
         { emoji: "🇦🇴", name: "Angola" },
         { emoji: "🇦🇶", name: "Antarctica" },
         { emoji: "🇦🇷", name: "Argentina" },
         { emoji: "🇦🇸", name: "American Samoa" },
         { emoji: "🇦🇹", name: "Austria" },
         { emoji: "🇦🇺", name: "Australia" },
         { emoji: "🇦🇼", name: "Aruba" },
         { emoji: "🇦🇽", name: "Åland Islands" },
         { emoji: "🇦🇿", name: "Azerbaijan" },
         { emoji: "🇧🇦", name: "Bosnia & Herzegovina" },
         { emoji: "🇧🇧", name: "Barbados" },
         { emoji: "🇧🇩", name: "Bangladesh" },
         { emoji: "🇧🇪", name: "Belgium" },
         { emoji: "🇧🇫", name: "Burkina Faso" },
         { emoji: "🇧🇬", name: "Bulgaria" },
         { emoji: "🇧🇭", name: "Bahrain" },
         { emoji: "🇧🇮", name: "Burundi" },
         { emoji: "🇧🇯", name: "Benin" },
         { emoji: "🇧🇱", name: "St. Barthélemy" },
         { emoji: "🇧🇲", name: "Bermuda" },
         { emoji: "🇧🇳", name: "Brunei" },
         { emoji: "🇧🇴", name: "Bolivia" },
         { emoji: "🇧🇶", name: "Caribbean Netherlands" },
         { emoji: "🇧🇷", name: "Brazil" },
         { emoji: "🇧🇸", name: "Bahamas" },
         { emoji: "🇧🇹", name: "Bhutan" },
         { emoji: "🇧🇻", name: "Bouvet Island" },
         { emoji: "🇧🇼", name: "Botswana" },
         { emoji: "🇧🇾", name: "Belarus" },
         { emoji: "🇧🇿", name: "Belize" },
         { emoji: "🇨🇦", name: "Canada" },
         { emoji: "🇨🇨", name: "Cocos (Keeling) Islands" },
         { emoji: "🇨🇩", name: "Congo - Kinshasa" },
         { emoji: "🇨🇫", name: "Central African Republic" },
         { emoji: "🇨🇬", name: "Congo - Brazzaville" },
         { emoji: "🇨🇭", name: "Switzerland" },
         { emoji: "🇨🇮", name: "Côte d’Ivoire" },
         { emoji: "🇨🇰", name: "Cook Islands" },
         { emoji: "🇨🇱", name: "Chile" },
         { emoji: "🇨🇲", name: "Cameroon" },
         { emoji: "🇨🇳", name: "China" },
         { emoji: "🇨🇴", name: "Colombia" },
         { emoji: "🇨🇵", name: "Clipperton Island" },
         { emoji: "🇨🇷", name: "Costa Rica" },
         { emoji: "🇨🇺", name: "Cuba" },
         { emoji: "🇨🇻", name: "Cape Verde" },
         { emoji: "🇨🇼", name: "Curaçao" },
         { emoji: "🇨🇽", name: "Christmas Island" },
         { emoji: "🇨🇾", name: "Cyprus" },
         { emoji: "🇨🇿", name: "Czechia" },
         { emoji: "🇩🇪", name: "Germany" },
         { emoji: "🇩🇬", name: "Diego Garcia" },
         { emoji: "🇩🇯", name: "Djibouti" },
         { emoji: "🇩🇰", name: "Denmark" },
         { emoji: "🇩🇲", name: "Dominica" },
         { emoji: "🇩🇴", name: "Dominican Republic" },
         { emoji: "🇩🇿", name: "Algeria" },
         { emoji: "🇪🇦", name: "Ceuta & Melilla" },
         { emoji: "🇪🇨", name: "Ecuador" },
         { emoji: "🇪🇪", name: "Estonia" },
         { emoji: "🇪🇬", name: "Egypt" },
         { emoji: "🇪🇭", name: "Western Sahara" },
         { emoji: "🇪🇷", name: "Eritrea" },
         { emoji: "🇪🇸", name: "Spain" },
         { emoji: "🇪🇹", name: "Ethiopia" },
         { emoji: "🇪🇺", name: "European Union" },
         { emoji: "🇫🇮", name: "Finland" },
         { emoji: "🇫🇯", name: "Fiji" },
         { emoji: "🇫🇰", name: "Falkland Islands" },
         { emoji: "🇫🇲", name: "Micronesia" },
         { emoji: "🇫🇴", name: "Faroe Islands" },
         { emoji: "🇫🇷", name: "France" },
         { emoji: "🇬🇦", name: "Gabon" },
         { emoji: "🇬🇧", name: "United Kingdom" },
         { emoji: "🇬🇩", name: "Grenada" },
         { emoji: "🇬🇪", name: "Georgia" },
         { emoji: "🇬🇫", name: "French Guiana" },
         { emoji: "🇬🇬", name: "Guernsey" },
         { emoji: "🇬🇭", name: "Ghana" },
         { emoji: "🇬🇮", name: "Gibraltar" },
         { emoji: "🇬🇱", name: "Greenland" },
         { emoji: "🇬🇲", name: "Gambia" },
         { emoji: "🇬🇳", name: "Guinea" },
         { emoji: "🇬🇵", name: "Guadeloupe" },
         { emoji: "🇬🇶", name: "Equatorial Guinea" },
         { emoji: "🇬🇷", name: "Greece" },
         { emoji: "🇬🇸", name: "South Georgia & South Sandwich Islands" },
         { emoji: "🇬🇹", name: "Guatemala" },
         { emoji: "🇬🇺", name: "Guam" },
         { emoji: "🇬🇼", name: "Guinea-Bissau" },
         { emoji: "🇬🇾", name: "Guyana" },
         { emoji: "🇭🇰", name: "Hong Kong SAR China" },
         { emoji: "🇭🇲", name: "Heard & McDonald Islands" },
         { emoji: "🇭🇳", name: "Honduras" },
         { emoji: "🇭🇷", name: "Croatia" },
         { emoji: "🇭🇹", name: "Haiti" },
         { emoji: "🇭🇺", name: "Hungary" },
         { emoji: "🇮🇨", name: "Canary Islands" },
         { emoji: "🇮🇩", name: "Indonesia" },
         { emoji: "🇮🇪", name: "Ireland" },
         { emoji: "🇮🇱", name: "Israel" },
         { emoji: "🇮🇲", name: "Isle of Man" },
         { emoji: "🇮🇳", name: "India" },
         { emoji: "🇮🇴", name: "British Indian Ocean Territory" },
         { emoji: "🇮🇶", name: "Iraq" },
         { emoji: "🇮🇷", name: "Iran" },
         { emoji: "🇮🇸", name: "Iceland" },
         { emoji: "🇮🇹", name: "Italy" },
         { emoji: "🇯🇪", name: "Jersey" },
         { emoji: "🇯🇲", name: "Jamaica" },
         { emoji: "🇯🇴", name: "Jordan" },
         { emoji: "🇯🇵", name: "Japan" },
         { emoji: "🇰🇪", name: "Kenya" },
         { emoji: "🇰🇬", name: "Kyrgyzstan" },
         { emoji: "🇰🇭", name: "Cambodia" },
         { emoji: "🇰🇮", name: "Kiribati" },
         { emoji: "🇰🇲", name: "Comoros" },
         { emoji: "🇰🇳", name: "St. Kitts & Nevis" },
         { emoji: "🇰🇵", name: "North Korea" },
         { emoji: "🇰🇷", name: "South Korea" },
         { emoji: "🇰🇼", name: "Kuwait" },
         { emoji: "🇰🇾", name: "Cayman Islands" },
         { emoji: "🇰🇿", name: "Kazakhstan" },
         { emoji: "🇱🇦", name: "Laos" },
         { emoji: "🇱🇧", name: "Lebanon" },
         { emoji: "🇱🇨", name: "St. Lucia" },
         { emoji: "🇱🇮", name: "Liechtenstein" },
         { emoji: "🇱🇰", name: "Sri Lanka" },
         { emoji: "🇱🇷", name: "Liberia" },
         { emoji: "🇱🇸", name: "Lesotho" },
         { emoji: "🇱🇹", name: "Lithuania" },
         { emoji: "🇱🇺", name: "Luxembourg" },
         { emoji: "🇱🇻", name: "Latvia" },
         { emoji: "🇱🇾", name: "Libya" },
         { emoji: "🇲🇦", name: "Morocco" },
         { emoji: "🇲🇨", name: "Monaco" },
         { emoji: "🇲🇩", name: "Moldova" },
         { emoji: "🇲🇪", name: "Montenegro" },
         { emoji: "🇲🇫", name: "St. Martin" },
         { emoji: "🇲🇬", name: "Madagascar" },
         { emoji: "🇲🇭", name: "Marshall Islands" },
         { emoji: "🇲🇰", name: "Macedonia" },
         { emoji: "🇲🇱", name: "Mali" },
         { emoji: "🇲🇲", name: "Myanmar (Burma)" },
         { emoji: "🇲🇳", name: "Mongolia" },
         { emoji: "🇲🇴", name: "Macau SAR China" },
         { emoji: "🇲🇵", name: "Northern Mariana Islands" },
         { emoji: "🇲🇶", name: "Martinique" },
         { emoji: "🇲🇷", name: "Mauritania" },
         { emoji: "🇲🇸", name: "Montserrat" },
         { emoji: "🇲🇹", name: "Malta" },
         { emoji: "🇲🇺", name: "Mauritius" },
         { emoji: "🇲🇻", name: "Maldives" },
         { emoji: "🇲🇼", name: "Malawi" },
         { emoji: "🇲🇽", name: "Mexico" },
         { emoji: "🇲🇾", name: "Malaysia" },
         { emoji: "🇲🇿", name: "Mozambique" },
         { emoji: "🇳🇦", name: "Namibia" },
         { emoji: "🇳🇨", name: "New Caledonia" },
         { emoji: "🇳🇪", name: "Niger" },
         { emoji: "🇳🇫", name: "Norfolk Island" },
         { emoji: "🇳🇬", name: "Nigeria" },
         { emoji: "🇳🇮", name: "Nicaragua" },
         { emoji: "🇳🇱", name: "Netherlands" },
         { emoji: "🇳🇴", name: "Norway" },
         { emoji: "🇳🇵", name: "Nepal" },
         { emoji: "🇳🇷", name: "Nauru" },
         { emoji: "🇳🇺", name: "Niue" },
         { emoji: "🇳🇿", name: "New Zealand" },
         { emoji: "🇴🇲", name: "Oman" },
         { emoji: "🇵🇦", name: "Panama" },
         { emoji: "🇵🇪", name: "Peru" },
         { emoji: "🇵🇫", name: "French Polynesia" },
         { emoji: "🇵🇬", name: "Papua New Guinea" },
         { emoji: "🇵🇭", name: "Philippines" },
         { emoji: "🇵🇰", name: "Pakistan" },
         { emoji: "🇵🇱", name: "Poland" },
         { emoji: "🇵🇲", name: "St. Pierre & Miquelon" },
         { emoji: "🇵🇳", name: "Pitcairn Islands" },
         { emoji: "🇵🇷", name: "Puerto Rico" },
         { emoji: "🇵🇸", name: "Palestinian Territories" },
         { emoji: "🇵🇹", name: "Portugal" },
         { emoji: "🇵🇼", name: "Palau" },
         { emoji: "🇵🇾", name: "Paraguay" },
         { emoji: "🇶🇦", name: "Qatar" },
         { emoji: "🇷🇪", name: "Réunion" },
         { emoji: "🇷🇴", name: "Romania" },
         { emoji: "🇷🇸", name: "Serbia" },
         { emoji: "🇷🇺", name: "Russia" },
         { emoji: "🇷🇼", name: "Rwanda" },
         { emoji: "🇸🇦", name: "Saudi Arabia" },
         { emoji: "🇸🇧", name: "Solomon Islands" },
         { emoji: "🇸🇨", name: "Seychelles" },
         { emoji: "🇸🇩", name: "Sudan" },
         { emoji: "🇸🇪", name: "Sweden" },
         { emoji: "🇸🇬", name: "Singapore" },
         { emoji: "🇸🇭", name: "St. Helena" },
         { emoji: "🇸🇮", name: "Slovenia" },
         { emoji: "🇸🇯", name: "Svalbard & Jan Mayen" },
         { emoji: "🇸🇰", name: "Slovakia" },
         { emoji: "🇸🇱", name: "Sierra Leone" },
         { emoji: "🇸🇲", name: "San Marino" },
         { emoji: "🇸🇳", name: "Senegal" },
         { emoji: "🇸🇴", name: "Somalia" },
         { emoji: "🇸🇷", name: "Suriname" },
         { emoji: "🇸🇸", name: "South Sudan" },
         { emoji: "🇸🇹", name: "São Tomé & Príncipe" },
         { emoji: "🇸🇻", name: "El Salvador" },
         { emoji: "🇸🇽", name: "Sint Maarten" },
         { emoji: "🇸🇾", name: "Syria" },
         { emoji: "🇸🇿", name: "Swaziland" },
         { emoji: "🇹🇦", name: "Tristan da Cunha" },
         { emoji: "🇹🇨", name: "Turks & Caicos Islands" },
         { emoji: "🇹🇩", name: "Chad" },
         { emoji: "🇹🇫", name: "French Southern Territories" },
         { emoji: "🇹🇬", name: "Togo" },
         { emoji: "🇹🇭", name: "Thailand" },
         { emoji: "🇹🇯", name: "Tajikistan" },
         { emoji: "🇹🇰", name: "Tokelau" },
         { emoji: "🇹🇱", name: "Timor-Leste" },
         { emoji: "🇹🇲", name: "Turkmenistan" },
         { emoji: "🇹🇳", name: "Tunisia" },
         { emoji: "🇹🇴", name: "Tonga" },
         { emoji: "🇹🇷", name: "Turkey" },
         { emoji: "🇹🇹", name: "Trinidad & Tobago" },
         { emoji: "🇹🇻", name: "Tuvalu" },
         { emoji: "🇹🇼", name: "Taiwan" },
         { emoji: "🇹🇿", name: "Tanzania" },
         { emoji: "🇺🇦", name: "Ukraine" },
         { emoji: "🇺🇬", name: "Uganda" },
         { emoji: "🇺🇳", name: "United Nations" },
         { emoji: "🇺🇸", name: "United States" },
         { emoji: "🇺🇾", name: "Uruguay" },
         { emoji: "🇺🇿", name: "Uzbekistan" },
         { emoji: "🇻🇦", name: "Vatican City" },
         { emoji: "🇻🇨", name: "St. Vincent & Grenadines" },
         { emoji: "🇻🇪", name: "Venezuela" },
         { emoji: "🇻🇬", name: "British Virgin Islands" },
         { emoji: "🇻🇮", name: "U.S. Virgin Islands" },
         { emoji: "🇻🇳", name: "Vietnam" },
         { emoji: "🇻🇺", name: "Vanuatu" },
         { emoji: "🇼🇫", name: "Wallis & Futuna" },
         { emoji: "🇼🇸", name: "Samoa" },
         { emoji: "🇽🇰", name: "Kosovo" },
         { emoji: "🇾🇪", name: "Yemen" },
         { emoji: "🇾🇹", name: "Mayotte" },
         { emoji: "🇿🇦", name: "South Africa" },
         { emoji: "🇿🇲", name: "Zambia" },
         { emoji: "🇿🇼", name: "Zimbabwe" },
      ],
   },
];
